kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mon-volume-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
    limits:
      storage: 50Mi
