apiVersion: apps/v1
kind: Deployment
metadata:
 name: weby
 labels:
  app: weby
spec:
 replicas: 7
 selector:
  matchLabels:
   app: weby
 template:
  metadata:
   labels:
    app: weby
  spec:
   containers:
   - name: weby
     image: bloby01/web:v1
     resources:
      requests:
       cpu: 500m
       memory: 128Mi
     livenessProbe:
      httpGet:
       path: /
       port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
     ports:
     - containerPort: 80
       name: http
       protocol: TCP
