apiVersion: v1
kind: Pod
metadata:
 name: apache2
spec:
 containers:
 - image: bloby01/web:v1
   env:
   - name: MaVariable
     valueFrom:
      configMapKeyRef:
       name: my-config
       key: cle1
   name: web-apache
   livenessProbe:
    httpGet:
     path: /
     port: 80
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 10
    failureThreshold: 3
   ports:
   - containerPort: 80
     name: http
     protocol: TCP
