apiVersion: apps/v1
kind: Deployment
metadata:
 name: w3
spec:
 replicas: 3
 selector:
  matchLabels:
   app: w3
 template:
  metadata:
   labels:
    app: w3
  spec:
   containers:
   - image: bloby01/web:v1
     name: w3
     livenessProbe:
      httpGet:
       path: /
       port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
     ports:
     - containerPort: 80
       name: http
       protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: w3
  name: w3
spec:
#  externalTrafficPolicy: Cluster
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: w3
  sessionAffinity: None
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web3
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`w3.mon.dom`) && PathPrefix(`/`)
    services:
    - name: web3
      port: 80
