apiVersion: apps/v1
kind: Deployment
metadata:
 name: w2
spec:
 replicas: 1
 selector:
  matchLabels:
   app: w2
 template:
  metadata:
   labels:
    app: w2
  spec:
   containers:
   - image: bloby01/web:v1
     name: w2
     readinessProbe:
      httpGet:
       path: /
       port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
     resources:
       requests:
         cpu: 60m
       limits:
         cpu: 60m
     ports:
     - containerPort: 80
       name: http
       protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: w2
  name: w2
spec:
#  externalTrafficPolicy: Cluster
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: w2
  sessionAffinity: None
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web2
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`w2.mon.dom`) && PathPrefix(`/`)
    services:
    - name: w2
      port: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: w2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: w2
  minReplicas: 4
  maxReplicas: 16
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
