apiVersion: apps/v1
kind: Deployment
metadata:
 name: w2
spec:
 replicas: 3
 selector:
  matchLabels:
   app: w2
 template:
  metadata:
   labels:
    app: w2
  spec:
   containers:
   - image: bloby01/web:v1
     name: w2
     livenessProbe:
      httpGet:
       path: /
       port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
     ports:
     - containerPort: 80
       name: http
       protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: w2
  name: w2
spec:
#  externalTrafficPolicy: Cluster
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: w2
  sessionAffinity: None
  status:
  loadBalancer: {}
