apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mon-service-manuel-slice
  namespace: default
  labels:
    kubernetes.io/service-name: mon-service  # ⚠️ Obligatoire !
addressType: IPv4
ports:
  - name: http
    port: 80
    protocol: TCP
endpoints:
  - addresses:
      - 10.0.0.42
    conditions:
      ready: true
