apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-pool-ip
  namespace: metallb-system
spec:
  addresses:
  - 172.21.0.1-172.21.0.99
  - 172.21.0.110-172.21.0.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
