apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels:
    volume: mon-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 172.21.0.100
    path: "/nfsshare"
