apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mybase
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      volume: mon-volume
