apiVersion: v1
kind: Pod
metadata:
  name: low-priority
spec:
  containers:
  - name: low-priority
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
