apiVersion: apps/v1
kind: Deployment
metadata:
 name: web-apache
spec:
 replicas: 3
 selector:
  matchLabels:
   toto: web1
 template:
  metadata:
   labels:
    toto: web1
  spec:
   containers:
   - image: bloby01/web:v1
     name: web-apache
     livenessProbe:
      httpGet:
       path: /
       port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
     ports:
     - containerPort: 80
       name: http
       protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: web-apache
spec:
  selector:
    toto: web1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
