apiVersion:   rbac.authorization.k8s.io/v1
kind:   Role
metadata:
 namespace:   preprod
 name:   john-pod-manage
rules:
- apiGroups:   [ "" ]
  resources:   [ "pods" ]
  verbs:   [ "get" ,   "watch" ,   "list",   "create",   "delete",   "update" ]
