apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-rolebinding
  namespace: preprod
subjects:
- kind: User
  name: John
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: John-pods-manager
  apiGroup: rbac.authorization.k8s.io
