apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: John-pods-manager-Rolebinding
  namespace: preprod
subjects:
- kind: User
  name: john
  namespace: preprod
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: John-pods-manager-Role
  apiGroup: rbac.authorization.k8s.io
