version: '3'
services:
 weby:
  deploy:
   replicas: 3
   endpoint_mode: dnsrr
  build: .
  command: python3 manage.py runserver 0.0.0.0:8000
  volumes:
   - django:/code
  ports:
   - "8000:8000"
  restart: always
  depends_on:
   - ddb
 ddb:
  image: postgres
  restart: always
volumes:
 django:
